import type { NextPage } from "next";
import React from 'react';
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useRouter } from 'next/router';
import ActiveLink from '../stories/ActiveLink';
import { IActiveLink } from "../common";






const Home: NextPage = () => {
  const router = useRouter();
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className={styles.main}>

      </main>
    </div>
  );
};

export default Home;
